import marimo

__generated_with = "0.23.9"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Symmetry Field Regressor (LMO)
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## About this repository & notebook

    This notebook focuses on src/pose6d module and requires the features to be already extracted. The steps are mention in Data processing.

    *you can also use the 'live docs' tab*

    ### Data ingestion
    - the dataset currently used is lmo, at the moment there'are no scripts to download the datasets automatically
    ### Data Access
    - LMOLoader is an abstraction for dataset access.
    ### Data processing:

    1. The script "script/pose6d_extract_pT.py" is used to extract a partial point clouds (pT) from the canonical objects found in the lmo dataset.
    2. After pT is available, "script/pose6d_extract_symmetry_features.py" can be run to compute a symmetry field over the canonical object and propagate the features via closest neighbour to the partial pointcloud.
    3. dGedi features can be computed using the external repository included as a module. There's a script availabe in "external/extract_dgedi_features.py" that can be run with the python venv given in the same folder.

    ``````bash
    # using python 3.12
    uv run ./script/pose6d_extract_pT.py
    uv run ./script/pose6d_extract_symmetry_features.py
    # using python 3.10: to use dgedi you need to explicitly invoke the env
    external/dgedi_env/bin/python external/extract_dgedi_features.py
    ``````
    This convoluted process its caused by an incompatibility between the original repository (3.12) and dGedi (3.10).

    ### Dataloader

    - pytorch dataset and dataloader targets the folders with the serialized partial point cloud (pT), target features (target) and dGedi features (input).

    The expected format is the same generated by data processing:

    - {dataset_name}/cache/points_pT
    - {dataset_name}/{experiment_name}/training/input
    - {dataset_name}/{experiment_name}/training/target
    """)
    return


@app.cell
def _():
    import marimo as mo
    from pose6d.config import LMOConfig, LMOPath
    from pose6d.loader import LMOLoader
    from pose6d.dataset_stats import print_summary_table, _dataset_summary
    from pose6d.dataset import SymmetryFieldPointDataset
    from pose6d.model import SymmetryFieldMLP
    from pathlib import Path
    import matplotlib.pyplot as plt
    import seaborn as sns
    import torch
    from torch.utils.data import DataLoader, Subset
    import json
    import glob
    import random

    # TODO: Check if data exist in the expected folders, throw an exception if not

    lmo_root = Path("/mnt/data/dev/dataset/tesis/BOP/lmo/lmo")

    ROOT = Path("/mnt/data/dev/dataset/tesis/6dpose")
    POINTS_PT_DIR = ROOT / "lmo/cache/points_pT/"
    FEATURES_INPUT_DIR = ROOT / "lmo/scalarfield/training/input/"
    TARGET_DIR = ROOT/ "lmo/scalarfield/training/target/"

    config = LMOConfig.from_root(lmo_root) 
    loader= LMOLoader(config) # uses only the 
    print_summary_table(_dataset_summary(loader, 2))

    return (
        DataLoader,
        FEATURES_INPUT_DIR,
        LMOLoader,
        POINTS_PT_DIR,
        Subset,
        SymmetryFieldMLP,
        SymmetryFieldPointDataset,
        TARGET_DIR,
        loader,
        mo,
        plt,
        random,
        sns,
        torch,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Training example - Point wise

    - Simple 2 layer MLP
    - 256 hidden dimension
    - ReLU
    - random batching
    """)
    return


@app.cell
def _(LMOLoader, SymmetryFieldPointDataset, random):

    # helper function to reserve some instances (pT pointclouds) for analysis.
    # returns a set of uids (internal ids generated by the data processing step). 
    # uses sets for fast lookups with set minus operator. 
    def reserve_test_uids(dataset: SymmetryFieldPointDataset, loader: LMOLoader, n_per_obj: int = 2, seed: int = 123) -> set[str]:
        rng = random.Random(seed)
        uids_by_obj: dict[int, list[str]] = {}
        for uid in dataset.uid_list:
            _, _, obj_id, _ = loader.parse_instance_uid(uid) # extract obj id
            uids_by_obj.setdefault(obj_id, []).append(uid) # populate the dictionary with obj_id: []

        test_uids = set()
        for obj_id, uids in uids_by_obj.items():
            test_uids.update(rng.sample(uids, min(n_per_obj, len(uids)))) # populate the set with random uids
        return test_uids

    return (reserve_test_uids,)


@app.cell
def _(
    DataLoader,
    FEATURES_INPUT_DIR,
    POINTS_PT_DIR,
    Subset,
    SymmetryFieldMLP,
    SymmetryFieldPointDataset,
    TARGET_DIR,
    loader,
    plt,
    reserve_test_uids,
    sns,
    torch,
):
    def exp1():
        dataset = SymmetryFieldPointDataset(POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR)

        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        test_uids = reserve_test_uids(dataset, loader, n_per_obj=2)
        train_uids = set(dataset.uid_list) - test_uids
        dataset.assign_split(train_uids=train_uids, val_uids=set(), test_uids=test_uids)

        # In this case, my 4G GPU is enough. 
        dataset.features = dataset.features.to(device)
        dataset.targets = dataset.targets.to(device)
    
        # split 0 = val, split 1 = train, split 2 = test
        train_idx = (dataset.split == 0).nonzero(as_tuple=True)[0]
        test_idx = (dataset.split == 2).nonzero(as_tuple=True)[0]
    
        train_loader = DataLoader(Subset(dataset, train_idx), batch_size=60000, shuffle=True)
    
        model = SymmetryFieldMLP(in_dim=dataset.features.shape[1]).to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
        loss_fn = torch.nn.MSELoss()
    
        loss_ = []
        LOG_ = 5
        N_EPOCHS = 250
        for epoch in range(N_EPOCHS):
            epoch_loss = 0.0
            for features, targets in train_loader:
                optimizer.zero_grad()
                pred = model(features)
                loss = loss_fn(pred, targets)
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()
            if epoch % LOG_ == 0:
                mean_epoch_loss = epoch_loss / len(train_loader)
                print(f"epoch {epoch}: loss={mean_epoch_loss:.6f}")
                loss_.append(mean_epoch_loss)

        sns.lineplot(x=list(range(0, N_EPOCHS, 5)), y = loss_)
        plt.title("Loss")
        plt.show()

    return (exp1,)


@app.cell
def _(exp1):
    exp1()

    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Training Example - Instance
    """)
    return


@app.cell
def _(
    DataLoader,
    FEATURES_INPUT_DIR,
    POINTS_PT_DIR,
    Subset,
    SymmetryFieldInstanceDataset,
    SymmetryFieldMLP,
    TARGET_DIR,
    loader,
    plt,
    reserve_test_uids,
    sns,
    symmetry_collate,
    torch,
):
    def exp2():
        dataset_inst = SymmetryFieldInstanceDataset(POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR)

        test_uids = reserve_test_uids(dataset_inst, loader, n_per_obj=2)
        train_uids = set(dataset_inst.uid_list) - test_uids
        dataset_inst.assign_split(train_uids=train_uids, val_uids=set(), test_uids=test_uids)
    
        train_indices = [
            i for i, s in enumerate(dataset_inst.split_per_instance) if s == 0
        ]
    
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
        train_loader_inst = DataLoader(
            Subset(dataset_inst, train_indices),
            batch_size=64,
            shuffle=True,
            collate_fn=symmetry_collate,
        )
    
        model_inst = SymmetryFieldMLP(in_dim=dataset_inst._features[0].shape[1]).to(device)
        optimizer_inst = torch.optim.Adam(model_inst.parameters(), lr=1e-3)
        loss_fn = torch.nn.MSELoss()
    
        loss_inst = []
        LOG_ = 25
        N_EPOCHS = 1000
        for epoch in range(N_EPOCHS):
            epoch_loss = 0.0
            for features, targets, batch_idx in train_loader_inst:
                features, targets = features.to(device), targets.to(device)
                optimizer_inst.zero_grad()
                pred = model_inst(features)
                loss = loss_fn(pred, targets)
                loss.backward()
                optimizer_inst.step()
                epoch_loss += loss.item()
            if epoch % LOG_ == 0:
                mean_epoch_loss = epoch_loss / len(train_loader_inst)
                print(f"epoch {epoch}: loss={mean_epoch_loss:.6f}")
                loss_inst.append(mean_epoch_loss)

        sns.lineplot(x=list(range(0, N_EPOCHS, 25)), y = loss_inst)
        plt.title("Loss")
        plt.show()

    return


if __name__ == "__main__":
    app.run()
