import marimo

__generated_with = "0.23.9"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Symmetry Field Regressor (LMO)
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## About this repository & notebook

    This notebook focuses on src/pose6d module and requires the features to be already extracted. The steps are mention in Data processing.

    *you can also use the 'live docs' tab*

    ### Data ingestion
    - the dataset currently used is lmo, at the moment there'are no scripts to download the datasets automatically
    ### Data Access
    - LMOLoader is an abstraction for dataset access.
    ### Data processing:

    1. The script "script/pose6d_extract_pT.py" is used to extract a partial point clouds (pT) from the canonical objects found in the lmo dataset.
    2. After pT is available, "script/pose6d_extract_symmetry_features.py" can be run to compute a symmetry field over the canonical object and propagate the features via closest neighbour to the partial pointcloud.
    3. dGedi features can be computed using the external repository included as a module. There's a script availabe in "external/extract_dgedi_features.py" that can be run with the python venv given in the same folder.

    ``````bash
    # using python 3.12
    uv run ./script/pose6d_extract_pT.py
    uv run ./script/pose6d_extract_symmetry_features.py
    # using python 3.10: to use dgedi you need to explicitly invoke the env
    external/dgedi_env/bin/python external/extract_dgedi_features.py
    ``````
    This convoluted process its caused by an incompatibility between the original repository (3.12) and dGedi (3.10).

    ### Dataloader

    - pytorch dataset and dataloader targets the folders with the serialized partial point cloud (pT), target features (target) and dGedi features (input).

    The expected format is the same generated by data processing:

    - {dataset_name}/cache/points_pT
    - {dataset_name}/{experiment_name}/training/input
    - {dataset_name}/{experiment_name}/training/target
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Config
    """)
    return


@app.cell
def _():
    import marimo as mo
    from pose6d.config import LMOConfig, LMOPath
    from pose6d.loader import LMOLoader
    from pose6d.dataset_stats import print_summary_table, _dataset_summary
    from pose6d.dataset import SymmetryFieldPointDataset, split_by_scene
    from pose6d.model import SymmetryFieldMLP
    from pose6d.geometry_utils import backproject_depth, transform_points
    from pose6d.preprocessing import extract_instances_pcs 

    from pathlib import Path
    import numpy as np
    import matplotlib.pyplot as plt
    import plotly.graph_objects as go
    import seaborn as sns
    import torch
    import trimesh
    from torch.utils.data import DataLoader, Subset
    import json
    import glob
    import random

    # TODO: Check if data exist in the expected folders, throw an exception if not
    lmo_root = Path("/mnt/data/dev/dataset/tesis/BOP/lmo/lmo")
    config = LMOConfig.from_root(lmo_root) 
    loader= LMOLoader(config) # uses only the 
    print_summary_table(_dataset_summary(loader, 2))
    return (
        LMOConfig,
        LMOLoader,
        Path,
        SymmetryFieldMLP,
        SymmetryFieldPointDataset,
        backproject_depth,
        config,
        extract_instances_pcs,
        go,
        loader,
        mo,
        np,
        plt,
        random,
        sns,
        split_by_scene,
        torch,
        transform_points,
        trimesh,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Functions
    """)
    return


@app.cell
def _(
    LMOConfig,
    LMOLoader,
    backproject_depth,
    extract_instances_pcs,
    go,
    np,
    transform_points,
    trimesh,
):
    # Visualization
    def plot_frame_meshes_and_sensor(loader: LMOLoader, config: LMOConfig, scene_id: int, img_id: int) -> None:
        K, depth_scale = loader.load_camera(scene_id, img_id)
        depth_image = loader.load_depth(scene_id, img_id)
        frame_point_cloud = backproject_depth(depth_image, K, depth_scale, stride=config.depth_stride)

        traces = [
            go.Scatter3d(
                x=frame_point_cloud[:, 0],
                y=frame_point_cloud[:, 1],
                z=frame_point_cloud[:, 2],
                mode="markers",
                marker=dict(size=1, color="gray", opacity=0.3),
                name="sensor",
            )
        ]

        instances = loader.load_instances(scene_id, img_id)
        for inst_idx, instance in enumerate(instances):
            mesh_path = config.paths.model_path(instance.obj_id)
            mesh = trimesh.load(mesh_path)

            posed_vertices = transform_points(mesh.vertices, instance.R, instance.t)
            faces = mesh.faces

            traces.append(
                go.Mesh3d(
                    x=posed_vertices[:, 0],
                    y=posed_vertices[:, 1],
                    z=posed_vertices[:, 2],
                    i=faces[:, 0],
                    j=faces[:, 1],
                    k=faces[:, 2],
                    opacity=1,
                    name=f"obj_{instance.obj_id} (inst {inst_idx})",
                    showlegend=True,
                )
            )

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=f"Scene {scene_id} / Frame {img_id}",
            height=700,
            scene=dict(aspectmode="data"),
        )
        fig.show()


    def plot_mesh_instance_visible(
        loader: LMOLoader,
        config,
        scene_id: int,
        img_id: int,
        inst_idx: int,
    ):
        instance = loader.load_instances(scene_id, img_id)[inst_idx]
        obj_id = instance.obj_id

        mesh_path = config.paths.model_path(instance.obj_id)
        mesh = trimesh.load(mesh_path)
        posed_vertices = transform_points(mesh.vertices, instance.R, instance.t)
        faces = mesh.faces

        traces = [
            go.Mesh3d(
                x=posed_vertices[:, 0],
                y=posed_vertices[:, 1],
                z=posed_vertices[:, 2],
                i=faces[:, 0],
                j=faces[:, 1],
                k=faces[:, 2],
                opacity=0.7,
                name=f"obj : {instance.obj_id} (instance {inst_idx})",
                showlegend=True,
            )
        ]

        pTr_iterator = extract_instances_pcs(loader, scene_id, img_id, [obj_id])
        uid, visib_posed_pcs = next(pTr_iterator)

        traces.append(
            go.Scatter3d(
                x=visib_posed_pcs[:, 0],
                y=visib_posed_pcs[:, 1],
                z=visib_posed_pcs[:, 2],
                mode="markers",
                marker=dict(size=2, color="yellow", opacity=0.5),
                name=f"Visible (instance {inst_idx})",
                showlegend=True,
            )
        )

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=f"Scene {scene_id} | Frame {img_id} | object {obj_id} | instance {inst_idx}",
            height=700,
            scene=dict(aspectmode="data"),
        )
        fig.show()


    def plot_mesh_instance_visible_with_field(
        loader: LMOLoader,
        config,
        scene_id: int,
        img_id: int,
        inst_idx: int,
        points: np.ndarray,
        symmetry_field: np.ndarray,
    ):
        instance = loader.load_instances(scene_id, img_id)[inst_idx]
        obj_id = instance.obj_id

        mesh_path = config.paths.model_path(instance.obj_id)
        mesh = trimesh.load(mesh_path)
        posed_vertices = transform_points(mesh.vertices, instance.R, instance.t)
        faces = mesh.faces

        traces = [
            go.Mesh3d(
                x=posed_vertices[:, 0],
                y=posed_vertices[:, 1],
                z=posed_vertices[:, 2],
                i=faces[:, 0],
                j=faces[:, 1],
                k=faces[:, 2],
                opacity=0.7,
                name=f"obj : {instance.obj_id} (instance {inst_idx})",
                showlegend=True,
            )
        ]

        traces.append(
            go.Scatter3d(
                x=points[:, 0],
                y=points[:, 1],
                z=points[:, 2],
                mode="markers",
                marker=dict(
                    size=3,
                    color=symmetry_field,
                    colorscale="Viridis",
                    showscale=True,
                    colorbar=dict(title="Symmetry field"),
                    opacity=0.8,
                ),
                name=f"Visible (instance {inst_idx})",
                showlegend=True,
            )
        )

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=f"Scene {scene_id} | Frame {img_id} | object {obj_id} | instance {inst_idx}",
            height=700,
            scene=dict(aspectmode="data"),
        )
        fig.show()


    def plot_object_point_cloud(loader: LMOLoader, obj_id: int, features: np.ndarray = None):
        pass


    def show_instance_segment(loader: LMOLoader, scene_id: int, img_id: int, obj_id: int, inst_idx: int):
        pass

    return (
        plot_frame_meshes_and_sensor,
        plot_mesh_instance_visible,
        plot_mesh_instance_visible_with_field,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Training example - Point wise

    - Simple 2 layer MLP
    - 256 hidden dimension
    - ReLU
    - random batching
    """)
    return


@app.cell
def _(
    LMOLoader,
    SymmetryFieldMLP,
    SymmetryFieldPointDataset,
    n_per_obj,
    plt,
    random,
    rng,
    sns,
    torch,
    uids_by_obj,
):
    def exp1_efficient(loader: LMOLoader, points_pt_dir, features_input_di, target_dir):
        # helper function to reserve some instances (pT pointclouds) for analysis.
        # returns a set of uids (internal ids generated by the data processing step). 
        # uses sets for fast lookups with set minus operator. 
        def reserve_test_uids(
            dataset: SymmetryFieldPointDataset,
            loader: LMOLoader,
            n_per_obj: int = 2,
            seed: int = 123) -> set[str]:

            rng = random.Random(seed)
            uids_by_obj: dict[int, list[str]] = {}
            for uid in dataset.uid_list:
                _, _, obj_id, _ = loader.parse_instance_uid(uid) # extract obj id
                uids_by_obj.setdefault(obj_id, []).append(uid) # populate the dictionary with obj_id: []

        test_uids = set()
        for obj_id, uids in uids_by_obj.items():
            test_uids.update(rng.sample(uids, min(n_per_obj, len(uids)))) # populate the set with random uids
        return test_uids
        dataset = SymmetryFieldPointDataset(points_pt_dir, features_input_di, target_dir)

        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Splits 
        test_uids = reserve_test_uids(dataset, loader, n_per_obj=2)
        train_uids = set(dataset.uid_list) - test_uids
        dataset.assign_split(train_uids=train_uids, val_uids=set(), test_uids=test_uids)

        # Masks (train = 0, val = 1, test = 2)
        train_mask = dataset.split == 0
        test_mask  = dataset.split == 2

        # Move data to GPU
        # TODO: looking into options in case VRAM is not sufficient (for now order of 100mb are needed)
        train_features = dataset.features[train_mask].to(device)
        train_targets  = dataset.targets[train_mask].to(device)
        test_features = dataset.features[test_mask].to(device)
        test_targets  = dataset.targets[test_mask].to(device)

        # Load model
        model = SymmetryFieldMLP(in_dim=train_features.shape[1]).to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
        loss_fn = torch.nn.MSELoss()

        # hypr parameters
        batch_size = 60000
        n_epochs = 250
        log_every = 5

        # calculate total batches
        n_train = train_features.shape[0]
        n_batches = (n_train + batch_size - 1) // batch_size

        # loss history for plotting
        loss_history = []
        for epoch in range(n_epochs):
            # Shuffle using a random permutation. A different one is used in every epoch
            perm = torch.randperm(n_train, device=device)
            epoch_loss = .0

            for i in range(n_batches):
                start = i * batch_size
                end = min(start + batch_size, n_train)
                perm_mask = perm[start:end] # obtain a slice of the permutation ()

                features = train_features[perm_mask] # index dgedi features
                targets = train_targets[perm_mask] # index symm features

                optimizer.zero_grad()
                pred = model(features) # make prediction
                loss = loss_fn(pred, targets) # calculate loss
                loss.backward() # propagate
                optimizer.step()

                epoch_loss += loss.item()

            mean_epoch_loss = epoch_loss / n_batches

            if epoch % log_every == 0: # log every k to avoid spamming the console
                print(f"epoch {epoch}: loss={mean_epoch_loss:.4f}")
                loss_history.append(mean_epoch_loss) # append to history

        # Using hold out frames to test prediction. It is not expected to generalize. 
        model.eval()
        with torch.no_grad():
            test_pred = model(test_features)
            test_loss = loss_fn(test_pred, test_targets).item()
        print(f"Test loss: {test_loss:.4f}")

        sns.lineplot(x=list(range(0, n_epochs, log_every)), y=loss_history)
        plt.title("Loss")
        plt.show()

    return (exp1_efficient,)


@app.cell
def _(Path):
    # -- Example configuration
    ROOT = Path("/mnt/data/dev/dataset/tesis/6dpose")
    POINTS_PT_DIR = ROOT / "lmo/cache/points_pT/"
    FEATURES_INPUT_DIR = ROOT / "lmo/scalarfield/training/input/"
    TARGET_DIR = ROOT/ "lmo/scalarfield/training/target/"
    return FEATURES_INPUT_DIR, POINTS_PT_DIR, ROOT, TARGET_DIR


@app.cell
def _(config, loader, plot_frame_meshes_and_sensor):
    plot_frame_meshes_and_sensor(loader, config, 2, 47 )
    return


@app.cell
def _(config, loader, plot_mesh_instance_visible):
    plot_mesh_instance_visible(loader, config, 2, 47, 5)
    return


@app.cell
def _(FEATURES_INPUT_DIR, POINTS_PT_DIR, TARGET_DIR, exp1_efficient, loader):
    exp1_efficient(loader, POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Experiment: Predict instances symmetry fields

    - LMODataset
    - Using scenes ... for training
    - testing with scene 2
    - Simple MLP
    """)
    return


@app.cell
def _(
    LMOLoader,
    SymmetryFieldMLP,
    SymmetryFieldPointDataset,
    plt,
    sns,
    split_by_scene,
    torch,
):
    def exp2(loader: LMOLoader, points_pt_dir, features_input_di, target_dir):

        dataset = SymmetryFieldPointDataset(
            points_pt_dir,
            features_input_di,
            target_dir,
            max_instances=850,
            test_scenes={2}, # Forces loading of all tests scenes
            include_all_test=True # forces all test scenes to load,
        )
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Splits (train/val = scenes 10,11 80/20 distribution; test = scene 2)
        train_uids, val_uids, test_uids = split_by_scene(
            dataset, test_scenes={2}, val_frac=0.2
        )
        print(f"train uids:{len(train_uids)}, " f"val uids:{len(val_uids)}, " f"test uids:{len(test_uids)}"  )
        # this re distributes train / val / test uids and point clouds + applies normalization with training scenes only
        dataset.assign_split(train_uids=train_uids, val_uids=val_uids, test_uids=test_uids)

        # Masks (train = 0, val = 1, test = 2)
        train_mask = dataset.split == 0
        test_mask = dataset.split == 2

        # Move data to GPU
        # TODO: looking into options in case VRAM is not sufficient (for now order of 100mb are needed)
        train_features = dataset.features[train_mask].to(device)
        train_targets = dataset.targets[train_mask].to(device)
        test_features = dataset.features[test_mask].to(device)
        test_targets = dataset.targets[test_mask].to(device)

        # Load model
        print(train_features.shape[1], train_features.shape[0])
        model = SymmetryFieldMLP(in_dim=train_features.shape[1]).to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
        loss_fn = torch.nn.MSELoss()

        # hyper parameters
        batch_size = 30000
        n_epochs = 125
        log_every = 5

        n_train = train_features.shape[0]
        n_batches = (n_train + batch_size - 1) // batch_size

        loss_history = []
        for epoch in range(n_epochs):
            perm = torch.randperm(n_train, device=device)
            epoch_loss = 0.0
            for i in range(n_batches):
                start = i * batch_size
                end = min(start + batch_size, n_train)
                perm_mask = perm[start:end]
                features = train_features[perm_mask]
                targets = train_targets[perm_mask]

                optimizer.zero_grad()
                pred = model(features)
                loss = loss_fn(pred, targets)
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()

            mean_epoch_loss = epoch_loss / n_batches
            if epoch % log_every == 0:
                print(f"epoch {epoch}: loss={mean_epoch_loss:.4f}")
                loss_history.append(mean_epoch_loss)

        model.eval()
        with torch.no_grad():
            test_pred = model(test_features)
            test_loss = loss_fn(test_pred, test_targets).item()
        print(f"Test loss: {test_loss:.4f}")


        sns.lineplot(x=list(range(0, n_epochs, log_every)), y=loss_history)
        plt.title("Loss")
        plt.show()

    return (exp2,)


@app.cell
def _(ROOT, config, loader, np, plot_mesh_instance_visible_with_field):
    # -- Experiment 2
    POINTS_PT_DIR_FULL = ROOT / "lmo/cache/points_pT/"
    FEATURES_INPUT_DIR_FULL = ROOT / "lmo/scalarfield_full/training/input/"
    TARGET_DIR_FULL = ROOT/ "lmo/scalarfield_full/training/target/"
    scene_id, img_id, obj_id, inst_idx = 10, 0, 10, 0
    # load file from system
    symmetry_field_ = np.load(TARGET_DIR_FULL/ (loader.instance_uid(scene_id, img_id, obj_id, inst_idx) + ".npz") )["target"]
    points_ = np.load(POINTS_PT_DIR_FULL/ (loader.instance_uid(scene_id, img_id, obj_id, inst_idx) + ".npz") )["points"]
    plot_mesh_instance_visible_with_field(loader, config, scene_id, img_id, inst_idx, points_, symmetry_field_)
    return FEATURES_INPUT_DIR_FULL, POINTS_PT_DIR_FULL, TARGET_DIR_FULL


@app.cell
def _(
    FEATURES_INPUT_DIR_FULL,
    POINTS_PT_DIR_FULL,
    TARGET_DIR_FULL,
    exp2,
    loader,
):
    exp2(loader, POINTS_PT_DIR_FULL, FEATURES_INPUT_DIR_FULL, TARGET_DIR_FULL)
    return


if __name__ == "__main__":
    app.run()
