import marimo

__generated_with = "0.23.9"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Symmetry Field Regressor (LMO)
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## About this repository & notebook

    This notebook focuses on src/pose6d module and requires the features to be already extracted. The steps are mention in Data processing.

    *you can also use the 'live docs' tab*

    ### Data ingestion
    - the dataset currently used is lmo, at the moment there'are no scripts to download the datasets automatically
    ### Data Access
    - LMOLoader is an abstraction for dataset access.
    ### Data processing:

    1. The script "script/pose6d_extract_pT.py" is used to extract a partial point clouds (pT) from the canonical objects found in the lmo dataset.
    2. After pT is available, "script/pose6d_extract_symmetry_features.py" can be run to compute a symmetry field over the canonical object and propagate the features via closest neighbour to the partial pointcloud.
    3. dGedi features can be computed using the external repository included as a module. There's a script availabe in "external/extract_dgedi_features.py" that can be run with the python venv given in the same folder.

    ``````bash
    # using python 3.12
    uv run ./script/pose6d_extract_pT.py
    uv run ./script/pose6d_extract_symmetry_features.py
    # using python 3.10: to use dgedi you need to explicitly invoke the env
    external/dgedi_env/bin/python external/extract_dgedi_features.py
    ``````
    This convoluted process its caused by an incompatibility between the original repository (3.12) and dGedi (3.10).

    ### Dataloader

    - pytorch dataset and dataloader targets the folders with the serialized partial point cloud (pT), target features (target) and dGedi features (input).

    The expected format is the same generated by data processing:

    - {dataset_name}/cache/points_pT
    - {dataset_name}/{experiment_name}/training/input
    - {dataset_name}/{experiment_name}/training/target
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Config
    """)
    return


@app.cell
def _():
    import marimo as mo
    from pose6d.config import LMOConfig, LMOPath
    from pose6d.loader import LMOLoader
    from pose6d.dataset_stats import print_summary_table, _dataset_summary
    from pose6d.dataset import SymmetryFieldInstanceDataset, split_by_scene
    from pose6d.model import SymmetryFieldMLP
    from pose6d.geometry_utils import backproject_depth, transform_points
    from pose6d.preprocessing import extract_instances_pcs 
    from logger import notebook_logger as log

    import numpy as np
    import matplotlib.pyplot as plt
    import plotly.graph_objects as go
    import seaborn as sns
    import pandas as pd
    import torch
    import trimesh
    from torch.utils.data import DataLoader, Subset
    from sklearn.decomposition import PCA
    import json
    import glob
    import random
    from pathlib import Path
    # TODO: Check if data exist in the expected folders, throw an exception if not
    lmo_root = Path("/mnt/data/dev/dataset/tesis/BOP/lmo/lmo")
    config = LMOConfig.from_root(lmo_root) 
    loader= LMOLoader(config) # uses only the 
    print_summary_table(_dataset_summary(loader, 2))
    return (
        DataLoader,
        LMOConfig,
        LMOLoader,
        PCA,
        Path,
        Subset,
        SymmetryFieldInstanceDataset,
        SymmetryFieldMLP,
        backproject_depth,
        config,
        extract_instances_pcs,
        go,
        loader,
        log,
        mo,
        np,
        pd,
        plt,
        random,
        sns,
        split_by_scene,
        torch,
        transform_points,
        trimesh,
    )


@app.cell
def _(Path, SymmetryFieldMLP, loader):
    import mlflow

    from experiments.mlflow_wrapper import run_experiment      # ajustá el path si lo dejaste en otro módulo
    from experiments.experiment_setup import setup_exp1
    from experiments.experiment_training import training_function

    mlflow.set_tracking_uri("http://localhost:5000")   # el mismo que tuneleaste por ssh
    mlflow.set_experiment("experiment_1_10")

    ROOT = Path("/mnt/data/dev/dataset/tesis/6dpose")
    POINTS_PT_DIR = ROOT / "lmo/cache/points_pT/"
    FEATURES_INPUT_DIR = ROOT / "lmo/scalarfield/training/input/"
    TARGET_DIR = ROOT/ "lmo/scalarfield/training/target/"
    base_setup = dict(
        loader=loader,
        points_pt_dir=POINTS_PT_DIR,
        features_input_di=FEATURES_INPUT_DIR,
        target_dir=TARGET_DIR,
        sel_obj_id=10,
        model_cls=SymmetryFieldMLP,
    )

    return (
        FEATURES_INPUT_DIR,
        POINTS_PT_DIR,
        ROOT,
        TARGET_DIR,
        base_setup,
        mlflow,
        run_experiment,
        setup_exp1,
        training_function,
    )


@app.cell
def _(base_setup, torch):


    configs = [
        dict(experiment_name="experiment_1_10", run_name="batch_16",
             setup_conf={**base_setup, "batch_size": 16},
             train_conf={}),

        dict(experiment_name="experiment_1_10", run_name="batch_32",
             setup_conf={**base_setup, "batch_size": 32},
             train_conf={}),

        dict(experiment_name="experiment_1_10", run_name="batch_64",
             setup_conf={**base_setup, "batch_size": 64},
             train_conf={}),

        dict(experiment_name="experiment_1_10", run_name="sgd_cosine_b16",
             setup_conf={**base_setup, "batch_size": 16},
             train_conf=dict(
                 optimizer_cls=torch.optim.SGD,
                 optimizer_kwargs={"lr": 1e-2, "momentum": 0.9},
                 scheduler_cls=torch.optim.lr_scheduler.CosineAnnealingLR,
                 scheduler_kwargs={"T_max": 250},
             )),

        dict(experiment_name="experiment_1_10", run_name="adamw_b16",
             setup_conf={**base_setup, "batch_size": 16},
             train_conf=dict(
                 optimizer_cls=torch.optim.AdamW,
                 optimizer_kwargs={"lr": 1e-3, "weight_decay": 1e-4},
             )),

    ]
    return (configs,)


@app.cell
def _(configs, run_experiment, setup_exp1, training_function):
    results = {}

    for cfg in configs:
        loss_hist, test_hist, model, dataset = run_experiment(cfg, setup_exp1, training_function)
        results[cfg["run_name"]] = {
            "loss_hist": loss_hist,
            "test_hist": test_hist,
            "model": model,
            "dataset": dataset,
        }
    return dataset, model


@app.cell
def _(
    FEATURES_INPUT_DIR,
    POINTS_PT_DIR,
    SymmetryFieldMLP,
    TARGET_DIR,
    base_setup,
    loader,
    mlflow,
    run_experiment,
    setup_exp1,
    torch,
    training_function,
):
    mlflow.set_experiment("experiment_1_11")

    base_setup_11 = dict(
        loader=loader,
        points_pt_dir=POINTS_PT_DIR,
        features_input_di=FEATURES_INPUT_DIR,
        target_dir=TARGET_DIR,
        sel_obj_id=11,
        model_cls=SymmetryFieldMLP,
    )
    configs_11 = [
        dict(experiment_name="experiment_1_11", run_name="batch_16",
             setup_conf={**base_setup, "batch_size": 16},
             train_conf={}),

        dict(experiment_name="experiment_1_11", run_name="batch_32",
             setup_conf={**base_setup, "batch_size": 32},
             train_conf={}),

        dict(experiment_name="experiment_1_11", run_name="batch_64",
             setup_conf={**base_setup, "batch_size": 64},
             train_conf={}),

        dict(experiment_name="experiment_1_11", run_name="sgd_cosine_b16",
             setup_conf={**base_setup, "batch_size": 16},
             train_conf=dict(
                 optimizer_cls=torch.optim.SGD,
                 optimizer_kwargs={"lr": 1e-2, "momentum": 0.9},
                 scheduler_cls=torch.optim.lr_scheduler.CosineAnnealingLR,
                 scheduler_kwargs={"T_max": 250},
             )),

        dict(experiment_name="experiment_1_11", run_name="adamw_b16",
             setup_conf={**base_setup, "batch_size": 16},
             train_conf=dict(
                 optimizer_cls=torch.optim.AdamW,
                 optimizer_kwargs={"lr": 1e-3, "weight_decay": 1e-4},
             )),

    ]
    results_11 = {}

    for cfg_ in configs_11:
        loss_hist_, test_hist_, model_, dataset_ = run_experiment(cfg_, setup_exp1, training_function)
        results_11[cfg_["run_name"]] = {
            "loss_hist": loss_hist_,
            "test_hist": test_hist_,
            "model": model_,
            "dataset": dataset_,
        }
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ##
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Functions
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Visualization
    """)
    return


@app.cell
def _(
    LMOConfig,
    LMOLoader,
    PCA,
    backproject_depth,
    extract_instances_pcs,
    go,
    np,
    plt,
    sns,
    transform_points,
    trimesh,
):
    # Visualization
    def plot_frame_meshes_and_sensor(loader: LMOLoader, config: LMOConfig, scene_id: int, img_id: int) -> None:
        K, depth_scale = loader.load_camera(scene_id, img_id)
        depth_image = loader.load_depth(scene_id, img_id)
        frame_point_cloud = backproject_depth(depth_image, K, depth_scale, stride=config.depth_stride)

        traces = [
            go.Scatter3d(
                x=frame_point_cloud[:, 0],
                y=frame_point_cloud[:, 1],
                z=frame_point_cloud[:, 2],
                mode="markers",
                marker=dict(size=1, color="gray", opacity=0.3),
                name="sensor",
            )
        ]

        instances = loader.load_instances(scene_id, img_id)
        for inst_idx, instance in enumerate(instances):
            mesh_path = config.paths.model_path(instance.obj_id)
            mesh = trimesh.load(mesh_path)

            posed_vertices = transform_points(mesh.vertices, instance.R, instance.t)
            faces = mesh.faces

            traces.append(
                go.Mesh3d(
                    x=posed_vertices[:, 0],
                    y=posed_vertices[:, 1],
                    z=posed_vertices[:, 2],
                    i=faces[:, 0],
                    j=faces[:, 1],
                    k=faces[:, 2],
                    opacity=1,
                    name=f"obj_{instance.obj_id} (inst {inst_idx})",
                    showlegend=True,
                )
            )

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=f"Scene {scene_id} / Frame {img_id}",
            height=700,
            scene=dict(aspectmode="data"),
        )
        fig.show()


    def plot_mesh_instance_visible(
        loader: LMOLoader,
        config,
        scene_id: int,
        img_id: int,
        inst_idx: int,
    ):
        instance = loader.load_instances(scene_id, img_id)[inst_idx]
        obj_id = instance.obj_id

        mesh_path = config.paths.model_path(instance.obj_id)
        mesh = trimesh.load(mesh_path)
        posed_vertices = transform_points(mesh.vertices, instance.R, instance.t)
        faces = mesh.faces

        traces = [
            go.Mesh3d(
                x=posed_vertices[:, 0],
                y=posed_vertices[:, 1],
                z=posed_vertices[:, 2],
                i=faces[:, 0],
                j=faces[:, 1],
                k=faces[:, 2],
                opacity=0.7,
                name=f"obj : {instance.obj_id} (instance {inst_idx})",
                showlegend=True,
            )
        ]

        pTr_iterator = extract_instances_pcs(loader, scene_id, img_id, [obj_id])
        uid, visib_posed_pcs = next(pTr_iterator)

        traces.append(
            go.Scatter3d(
                x=visib_posed_pcs[:, 0],
                y=visib_posed_pcs[:, 1],
                z=visib_posed_pcs[:, 2],
                mode="markers",
                marker=dict(size=2, color="yellow", opacity=0.5),
                name=f"Visible (instance {inst_idx})",
                showlegend=True,
            )
        )

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=f"Scene {scene_id} | Frame {img_id} | object {obj_id} | instance {inst_idx}",
            height=700,
            scene=dict(aspectmode="data"),
        )
        fig.show()


    def plot_mesh_instance_visible_with_field(
        loader: LMOLoader,
        config,
        scene_id: int,
        img_id: int,
        inst_idx: int,
        points: np.ndarray,
        symmetry_field: np.ndarray,
    ):
        instance = loader.load_instances(scene_id, img_id)[inst_idx]
        obj_id = instance.obj_id

        mesh_path = config.paths.model_path(instance.obj_id)
        mesh = trimesh.load(mesh_path)
        posed_vertices = transform_points(mesh.vertices, instance.R, instance.t)
        faces = mesh.faces

        traces = [
            go.Mesh3d(
                x=posed_vertices[:, 0],
                y=posed_vertices[:, 1],
                z=posed_vertices[:, 2],
                i=faces[:, 0],
                j=faces[:, 1],
                k=faces[:, 2],
                opacity=0.7,
                name=f"obj : {instance.obj_id} (instance {inst_idx})",
                showlegend=True,
                color="orange"
            )
        ]

        traces.append(
            go.Scatter3d(
                x=points[:, 0],
                y=points[:, 1],
                z=points[:, 2],
                mode="markers",
                marker=dict(
                    size=3,
                    color=symmetry_field,
                    colorscale="Viridis",
                    showscale=True,
                    colorbar=dict(title="Symmetry field"),
                    opacity=0.8,
                ),
                name=f"Visible (instance {inst_idx})",
                showlegend=True,
            )
        )

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=f"Scene {scene_id} | Frame {img_id} | object {obj_id} | instance {inst_idx}",
            height=700,
            scene=dict(aspectmode="data"),
        )
        fig.show()

    def features_to_rgb(
        features: np.ndarray,
        reference: np.ndarray | None = None,
        percentiles: tuple[float, float] = (2.0, 98.0),
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        features = np.asarray(features, dtype=np.float64)
        reference = features if reference is None else np.asarray(reference, dtype=np.float64)

        pca = PCA(n_components=3).fit(reference)
        signs = np.sign(pca.components_[np.arange(3), np.abs(pca.components_).argmax(axis=1)])
        signs[signs == 0] = 1.0
        pca.components_ *= signs[:, None]

        low, high = np.percentile(pca.transform(reference), percentiles, axis=0)
        span = np.where(high - low > 1e-12, high - low, 1.0)

        scaled = (pca.transform(features) - low) / span
        inside = np.all((scaled >= 0.0) & (scaled <= 1.0), axis=1)
        rgb = np.clip(scaled, 0.0, 1.0) * 255.0
        colors = np.array([f"rgb({int(r)},{int(g)},{int(b)})" for r, g, b in rgb])

        return colors, inside, pca.explained_variance_ratio_


    def plot_mesh_instance_with_dgedi_features(
        loader: LMOLoader,
        config,
        scene_id: int,
        img_id: int,
        inst_idx: int,
        points: np.ndarray,
        features: np.ndarray,
        reference: np.ndarray | None = None,
        show_mesh: bool = True,
        percentiles = (2.0, 98.0),
    ) -> go.Figure:

        instance = loader.load_instances(scene_id, img_id)[inst_idx]
        obj_id = instance.obj_id

        colors, inside, evr = features_to_rgb(features, reference, percentiles=percentiles)
        outside = ~inside

        traces = []
        if show_mesh:
            mesh = trimesh.load(config.paths.model_path(obj_id))
            posed_vertices = transform_points(mesh.vertices, instance.R, instance.t)
            faces = mesh.faces
            traces.append(
                go.Mesh3d(
                    x=posed_vertices[:, 0],
                    y=posed_vertices[:, 1],
                    z=posed_vertices[:, 2],
                    i=faces[:, 0],
                    j=faces[:, 1],
                    k=faces[:, 2],
                    opacity=0.3,
                    name=f"obj : {obj_id} (instance {inst_idx})",
                    showlegend=True,
                )
            )
        traces.append(
            go.Scatter3d(
                x=points[inside, 0],
                y=points[inside, 1],
                z=points[inside, 2],
                mode="markers",
                marker=dict(size=3, color=colors[inside].tolist(), opacity=0.9),
                name=f"dGeDi PCA ({int(inside.sum())} pts)",
                showlegend=True,
            )
        )
        if outside.any():
            traces.append(
                go.Scatter3d(
                    x=points[outside, 0],
                    y=points[outside, 1],
                    z=points[outside, 2],
                    mode="markers",
                    marker=dict(size=3, color="rgb(130,130,130)", symbol="x", opacity=0.9),
                    name=f"fuera de rango ({int(outside.sum())} pts)",
                    showlegend=True,
                )
            )

        evr_text = " | ".join(f"PC{i + 1}: {v:.1%}" for i, v in enumerate(evr))

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=(
                f"Scene {scene_id} | Frame {img_id} | object {obj_id} | instance {inst_idx}"
                f"<br><sup>RGB = PC1, PC2, PC3 &nbsp;&nbsp; {evr_text}</sup>"
            ),
            height=700,
            scene=dict(aspectmode="data"),
        )
        return fig


    def plot_loss(train_loss_history, val_loss_history, log: bool = True):
        fig, ax = plt.subplots(figsize=(7, 4))
        sns.lineplot(x=range(len(train_loss_history)), y=train_loss_history, label="train", ax=ax)
        sns.lineplot(x=range(len(val_loss_history)), y=val_loss_history, label="val", ax=ax)
        if log:
            ax.set_yscale("log")
        ax.set(xlabel="epoch", ylabel="loss", title="Curvas de entrenamiento")
        return fig


    def plot_error_by_object(df, metric: str = "rmse"):
        fig, ax = plt.subplots(figsize=(7, 4))
        sns.boxplot(data=df, x="obj_id", y=metric, ax=ax, showfliers=False)
        sns.stripplot(data=df, x="obj_id", y=metric, ax=ax, color="black", size=3, alpha=0.5)
        ax.set(xlabel="obj_id", ylabel=metric, title=f"{metric} por instancia, agrupado por objeto")
        return fig


    def plot_error_distribution(df, metric: str = "rmse"):
        fig, ax = plt.subplots(figsize=(7, 4))
        sns.histplot(data=df, x=metric, hue="obj_id", multiple="layer", bins=30, ax=ax)
        ax.set(xlabel=metric, ylabel="instancias", title=f"Distribución de {metric}")
        return fig


    def plot_error_vs_visibility(df, metric: str = "rmse"):
        fig, ax = plt.subplots(figsize=(7, 4))
        sns.scatterplot(data=df, x="visib_fract", y=metric, hue="obj_id", ax=ax)
        ax.set(xlabel="fracción visible", ylabel=metric, title=f"{metric} vs visibilidad")
        return fig


    def plot_pred_vs_target(df):
        fig, ax = plt.subplots(figsize=(5, 5))
        sns.scatterplot(data=df, x="target_mean", y="pred_mean", hue="obj_id", ax=ax)
        lo = min(df["target_mean"].min(), df["pred_mean"].min())
        hi = max(df["target_mean"].max(), df["pred_mean"].max())
        ax.plot([lo, hi], [lo, hi], "k--", linewidth=1)
        ax.set(xlabel="target medio", ylabel="predicción media", title="Media por instancia")
        return fig

    return (
        plot_error_by_object,
        plot_error_distribution,
        plot_error_vs_visibility,
        plot_loss,
        plot_mesh_instance_visible_with_field,
        plot_mesh_instance_with_dgedi_features,
        plot_pred_vs_target,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Statistics
    """)
    return


@app.cell
def _(LMOLoader, np, pd, torch):
    # Eval funtions
    @torch.no_grad()
    def evaluate_split(
        model: torch.nn.Module,
        dataset,
        split: int = 2,
        device: torch.device | str | None = None,
        loader: LMOLoader | None = None,
    ) -> pd.DataFrame:
        if device is None:
            device = next(model.parameters()).device

        model.eval()
        rows = []
        frame_cache: dict[tuple[int, int], list] = {}

        for idx, uid in enumerate(dataset.uid_list):
            if int(dataset.split_per_instance[idx]) != split:
                continue

            _, features, target_raw = dataset.get_instance(uid)
            pred_norm = model(features.to(device)).reshape(-1).cpu()
            pred = dataset.denormalize(pred_norm).numpy().astype(np.float64)
            target = target_raw.numpy().astype(np.float64)

            error = pred - target
            target_std = target.std()
            pred_std = pred.std()
            rmse = float(np.sqrt((error**2).mean()))

            if target_std > 1e-12 and pred_std > 1e-12:
                pearson = float(np.corrcoef(pred, target)[0, 1])
            else:
                pearson = np.nan

            scene_id, img_id, obj_id, inst_idx = LMOLoader.parse_instance_uid_(uid)

            row = {
                "uid": uid,
                "scene_id": scene_id,
                "img_id": img_id,
                "obj_id": obj_id,
                "inst_idx": inst_idx,
                "n_points": len(target),
                "mse": float((error**2).mean()),
                "mae": float(np.abs(error).mean()),
                "rmse": rmse,
                "rmse_norm": rmse / target_std if target_std > 1e-12 else np.nan,
                "bias": float(error.mean()),
                "pearson_r": pearson,
                "target_mean": float(target.mean()),
                "target_std": float(target_std),
                "pred_mean": float(pred.mean()),
                "pred_std": float(pred_std),
            }

            if loader is not None:
                key = (scene_id, img_id)
                if key not in frame_cache:
                    frame_cache[key] = loader.load_intances(scene_id, img_id)
                row["visib_fract"] = frame_cache[key][inst_idx].visible_fract

            rows.append(row)

        return pd.DataFrame(rows)

    return (evaluate_split,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Experiments
    """)
    return


@app.cell
def _(
    DataLoader,
    LMOLoader,
    Subset,
    SymmetryFieldInstanceDataset,
    SymmetryFieldMLP,
    SymmetryFieldPointDataset,
    log,
    plt,
    random,
    sns,
    split_by_scene,
    test_loss_history,
    torch,
):
    def reserve_test_uids(
        dataset: SymmetryFieldInstanceDataset,
        loader: LMOLoader,
        sel_obj_id,
        n_per_obj: int = 2,
        seed: int = 123,
        ) -> set[str]:
        rng = random.Random(seed)
        uids_by_obj: dict[int, list[str]] = {}
        for uid in dataset.uid_list:
            _, _, obj_id, _ = loader.parse_instance_uid(uid) # extract obj id
            if obj_id != sel_obj_id:
                continue
            uids_by_obj.setdefault(obj_id, []).append(uid) # populate the dictionary with obj_id: []
        test_uids = set()
        for obj_id, uids in uids_by_obj.items():
            test_uids.update(rng.sample(uids, min(n_per_obj, len(uids)))) # populate the set with random uids
        return test_uids

    def exp1_efficient(
        loader: LMOLoader,
        points_pt_dir,
        features_input_di,
        target_dir,
        optimizer_cls: type[torch.optim.Optimizer] = torch.optim.Adam,
        optimizer_kwargs: dict | None = None,
        scheduler_cls: type | None = None,
        scheduler_kwargs: dict | None = None,
        batch_size: int = 32,
        sel_obj_id = 10,
        n_epochs = 5000

    ):

        # dataset
        dataset = SymmetryFieldInstanceDataset(points_pt_dir, features_input_di, target_dir)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Splits

        test_uids = reserve_test_uids(dataset, loader, n_per_obj=5)
        print(test_uids)
        obj_target = f"obj{sel_obj_id:06d}"
        train_uids = set([x for x in dataset.uid_list if obj_target in x]) - test_uids
        dataset.assign_split(train_uids=train_uids, val_uids=set(), test_uids=test_uids)
        log.info(f"Training with {len(train_uids)} instances, Testing with {len(test_uids)} instances.")
        # Masks (train = 0, val = 1, test = 2)
        train_idx = (dataset.split == 0).nonzero(as_tuple=True)[0].tolist()
        test_idx = (dataset.split == 2).nonzero(as_tuple=True)[0].tolist()

        # hypr parameters
        n_epochs = n_epochs
        log_every = n_epochs // 250

        train_loader = DataLoader(Subset(dataset, train_idx), batch_size=batch_size, shuffle=True)

        # Load model
        feature_dim = dataset.features.shape[-1]
        model = SymmetryFieldMLP(in_dim=feature_dim).to(device)

        optimizer_kwargs = optimizer_kwargs or {}
        optimizer = optimizer_cls(model.parameters(), **optimizer_kwargs)

        scheduler = None
        if scheduler_cls is not None:
            scheduler_kwargs = scheduler_kwargs or {}
            scheduler = scheduler_cls(optimizer, **scheduler_kwargs)

        loss_fn = torch.nn.MSELoss()

        test_features = dataset.features[test_idx].to(device)
        test_targets = dataset.targets[test_idx].to(device)

        # loss history for plotting
        loss_history = []
        loss_test_history = []
        for epoch in range(n_epochs):
            epoch_loss = .0
            n_batches = 0

            for features, targets in train_loader:
                features = features.to(device) # (B, K, f)
                targets = targets.to(device) # (B, K)

                optimizer.zero_grad()
                pred = model(features.reshape(-1, feature_dim)).reshape(targets.shape) # (B, K)

                per_instance_mse = ((pred - targets) ** 2).mean(dim=1) # MSE per instance (B,)
                loss = per_instance_mse.mean() # Mean MSE

                loss.backward() # propagate
                optimizer.step()

                epoch_loss += loss.item()
                n_batches += 1

            if scheduler is not None:
                scheduler.step()

            mean_epoch_loss = epoch_loss / n_batches

            if epoch % log_every == 0: # log every k to avoid spamming the console
                model.eval()
                with torch.no_grad():
                    test_pred = model(test_features.reshape(-1, feature_dim)).reshape(test_targets.shape)
                    per_instance_test_mse = ((test_pred - test_targets) ** 2).mean(dim=1)
                    mean_test_loss = per_instance_test_mse.mean().item()
                model.train()

                print(f"epoch {epoch}: loss={mean_epoch_loss:.4f}  test_loss={mean_test_loss:.4f}")
                loss_history.append(mean_epoch_loss) # append to history
                loss_test_history.append(mean_test_loss)

        # Using hold out frames to test prediction. It is not expected to generalize.
        model.eval()
        with torch.no_grad():
            test_pred = model(test_features.reshape(-1, feature_dim)).reshape(test_targets.shape)
            per_instance_test_mse = ((test_pred - test_targets) ** 2).mean(dim=1)
            test_loss = per_instance_test_mse.mean().item()
        print(f"Test loss: {test_loss:.4f}")

        return n_epochs, loss_history, loss_test_history, model, dataset



    def exp2(
        loader: LMOLoader, points_pt_dir, features_input_di, target_dir
    ) -> tuple[SymmetryFieldPointDataset, SymmetryFieldMLP, list[float], list[float]]:
        TEST_SCENES = [2]
        dataset = SymmetryFieldPointDataset(
            points_pt_dir, features_input_di, target_dir,
            max_instances=850,
            include_all_test=True,  # forces all test scenes to load
            test_scenes=TEST_SCENES,
        )
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Splits (train/val = remaining scenes, 80/20 distribution; test = TEST_SCENES)
        train_uids, val_uids, test_uids = split_by_scene(
            dataset, test_scenes=set(TEST_SCENES), val_frac=0.2
        )
        print(
            f"train uids:{len(train_uids)}, "
            f"val uids:{len(val_uids)}, "
            f"test uids:{len(test_uids)}"
        )

        # this redistributes train/val/test uids and point clouds + applies
        # normalization with training scenes only
        dataset.assign_split(train_uids=train_uids, val_uids=val_uids, test_uids=test_uids)

        # Masks (train = 0, val = 1, test = 2)
        train_mask = dataset.split == 0
        val_mask = dataset.split == 1
        test_mask = dataset.split == 2

        # Move data to GPU
        train_features = dataset.features[train_mask].to(device)
        train_targets = dataset.targets[train_mask].to(device)
        val_features = dataset.features[val_mask].to(device)
        val_targets = dataset.targets[val_mask].to(device)
        test_features = dataset.features[test_mask].to(device)
        test_targets = dataset.targets[test_mask].to(device)

        # Load model
        print(train_features.shape[1], train_features.shape[0])
        model = SymmetryFieldMLP(in_dim=train_features.shape[1]).to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
        loss_fn = torch.nn.MSELoss()

        # hyper parameters
        batch_size = 25000
        n_epochs = 125
        log_every = 5

        n_train = train_features.shape[0]
        n_batches = (n_train + batch_size - 1) // batch_size

        train_loss_history = []
        val_loss_history = []

        for epoch in range(n_epochs):
            model.train()
            perm = torch.randperm(n_train, device=device)
            epoch_loss = 0.0
            for i in range(n_batches):
                start = i * batch_size
                end = min(start + batch_size, n_train)
                perm_mask = perm[start:end]
                features = train_features[perm_mask]
                targets = train_targets[perm_mask]

                optimizer.zero_grad()
                pred = model(features)
                loss = loss_fn(pred, targets)
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()

            mean_epoch_loss = epoch_loss / n_batches

            if epoch % log_every == 0:
                model.eval()
                with torch.no_grad():
                    val_pred = model(val_features)
                    val_loss = loss_fn(val_pred, val_targets).item()

                print(f"epoch {epoch}: train_loss={mean_epoch_loss:.4f}  val_loss={val_loss:.4f}")
                train_loss_history.append(mean_epoch_loss)
                val_loss_history.append(val_loss)

        model.eval()
        with torch.no_grad():
            test_pred = model(test_features)
            test_loss = loss_fn(test_pred, test_targets).item()
        print(f"Test loss: {test_loss:.4f}")

        epochs_logged = list(range(0, n_epochs, log_every))
        sns.lineplot(x=epochs_logged, y=train_loss_history, label="train")
        sns.lineplot(x=epochs_logged, y=val_loss_history, label="val")
        plt.title("Loss")
        plt.legend()
        plt.show()

        return dataset, model, train_loss_history, val_loss_history, test_loss_history

    return exp1_efficient, exp2


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Training example

    - Simple 2 layer MLP
    - 256 hidden dimension
    - ReLU
    - random batching
    """)
    return


@app.cell
def _(Path, config, loader, np, plot_mesh_instance_visible_with_field):
    # -- Example configuration
    ROOT = Path("/mnt/data/dev/dataset/tesis/6dpose")
    POINTS_PT_DIR = ROOT / "lmo/cache/points_pT/"
    FEATURES_INPUT_DIR = ROOT / "lmo/scalarfield/training/input/"
    TARGET_DIR = ROOT/ "lmo/scalarfield/training/target/"

    test = np.load("/mnt/data/dev/dataset/tesis/6dpose/lmo/cache/points_pT/scene000002_img000003_obj000010_inst05.npz")['points']
    symmetry_field_1 = np.load(TARGET_DIR/ (loader.instance_uid(2, 3, 10, 5) + ".npz") )["target"]
    plot_mesh_instance_visible_with_field(loader, config, 2, 3, 5, test, symmetry_field_1)
    print(test.size)
    return FEATURES_INPUT_DIR, POINTS_PT_DIR, ROOT, TARGET_DIR, test


@app.cell
def _(
    FEATURES_INPUT_DIR,
    config,
    loader,
    np,
    plot_mesh_instance_with_dgedi_features,
    test,
):
    features_dgedi = np.load(FEATURES_INPUT_DIR / ("scene000002_img000003_obj000010_inst05" + ".npz"))["features"]

    plot_mesh_instance_with_dgedi_features(
        loader, config, 2, 3, 5, test, features_dgedi, percentiles=(1.0, 99.0)
    )
    return


@app.cell
def _(
    FEATURES_INPUT_DIR,
    POINTS_PT_DIR,
    TARGET_DIR,
    exp1_efficient,
    loader,
    torch,
):
    # batches
    x_1, y_1, yt_1, model_1, dataset_exp1 = exp1_efficient(loader, POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR, batch_size=16)
    x_2, y_2,yt_2, model_2, _ = exp1_efficient(loader, POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR, batch_size=32)
    x_3, y_3,yt_3, model_3, _ = exp1_efficient(loader, POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR, batch_size=64)

    # optimizer + scheduler
    x_4, y_4,yt_4, model_4, _ = exp1_efficient(
        loader, POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR,
        optimizer_cls=torch.optim.SGD,
        optimizer_kwargs={"lr": 1e-2, "momentum": 0.9},
        scheduler_cls=torch.optim.lr_scheduler.CosineAnnealingLR,
        scheduler_kwargs={"T_max": 250},
        batch_size=16
    )

    x_5, y_5, yt_5, model_5, _ = exp1_efficient(
        loader, POINTS_PT_DIR, FEATURES_INPUT_DIR, TARGET_DIR,
        optimizer_cls=torch.optim.AdamW,
        optimizer_kwargs={"lr": 1e-3, "weight_decay": 1e-4},
        batch_size=16
    )
    return (
        dataset_exp1,
        model_1,
        x_1,
        y_1,
        y_2,
        y_3,
        y_4,
        y_5,
        yt_1,
        yt_2,
        yt_3,
        yt_4,
        yt_5,
    )


@app.cell
def _(plt, sns, x_1, y_1, y_2, y_3, y_4, y_5):
    x = list(range(0, x_1, 50))
    sns.lineplot(x=x, y=y_1, label="batch_16")
    sns.lineplot(x=x, y=y_2, label="batch_32")
    sns.lineplot(x=x, y=y_3, label="batch_64")
    sns.lineplot(x=x, y=y_4, label="batch_64_SGD_scheduler")
    sns.lineplot(x=x, y=y_5, label="batch_64_Wdecay")
    plt.title("Experiment 1 - batches & optimizers train")
    plt.xlabel("train epoch")
    plt.ylabel("loss")
    plt.legend()
    plt.show()
    return (x,)


@app.cell
def _(plt, sns, x, yt_1, yt_2, yt_3, yt_4, yt_5):
    sns.lineplot(x=x, y=yt_1, label="batch_16")
    sns.lineplot(x=x, y=yt_2, label="batch_32")
    sns.lineplot(x=x, y=yt_3, label="batch_64")
    sns.lineplot(x=x, y=yt_4, label="batch_64_SGD_scheduler")
    sns.lineplot(x=x, y=yt_5, label="batch_64_Wdecay")
    plt.title("Experiment 1 - batches & optimizers test")
    plt.xlabel("epoch")
    plt.ylabel("test loss")
    plt.legend()
    plt.show()
    return


@app.cell
def _(config, loader, plot_mesh_instance_visible_with_field, torch):
    def plotter_exp1_examples(id, dataset, model):
        uids = ['scene000002_img000175_obj000010_inst05', 'scene000002_img000224_obj000010_inst05', 'scene000002_img000625_obj000010_inst05', 'scene000002_img000096_obj000010_inst05', 'scene000002_img000909_obj000011_inst06', 'scene000002_img001099_obj000011_inst06', 'scene000002_img000039_obj000011_inst05', 'scene000002_img000809_obj000010_inst05', 'scene000002_img000428_obj000011_inst06', 'scene000002_img001131_obj000011_inst06']

        scene_id, img_id, obj_id, inst_idx = loader.parse_instance_uid(uids[id])
        points, features, target_raw = dataset.get_instance(uids[id])
        model.eval()
        with torch.no_grad():
            pred_normalized = model(features.to("cuda"))
            pred = dataset.denormalize(pred_normalized.cpu())
        plot_mesh_instance_visible_with_field(
            loader, config, scene_id, img_id, inst_idx,
            points.numpy(), pred.numpy(),
        )

    return (plotter_exp1_examples,)


@app.cell
def _(dataset_exp1, model_1, plotter_exp1_examples):
    plotter_exp1_examples(0, dataset_exp1, model_1)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Experiment: Predict instances symmetry fields

    - LMODataset
    - Using scenes ... for training
    - testing with scene 2
    - Simple MLP
    """)
    return


@app.cell
def _():
    return


@app.cell
def _(ROOT, config, loader, np, plot_mesh_instance_visible_with_field):
    # -- Experiment 2
    POINTS_PT_DIR_FULL = ROOT / "lmo/cache/points_pT/"
    FEATURES_INPUT_DIR_FULL = ROOT / "lmo/scalarfield_full/training/input/"
    TARGET_DIR_FULL = ROOT/ "lmo/scalarfield_full/training/target/"
    scene_id, img_id, obj_id, inst_idx = 2, 47, 10, 5
    # load file from system
    symmetry_field_ = np.load(TARGET_DIR_FULL/ (loader.instance_uid(scene_id, img_id, obj_id, inst_idx) + ".npz") )["target"]
    points_ = np.load(POINTS_PT_DIR_FULL/ (loader.instance_uid(scene_id, img_id, obj_id, inst_idx) + ".npz") )["points"]
    plot_mesh_instance_visible_with_field(loader, config, scene_id, img_id, inst_idx, points_, symmetry_field_)
    return (
        FEATURES_INPUT_DIR_FULL,
        POINTS_PT_DIR_FULL,
        TARGET_DIR_FULL,
        img_id,
        inst_idx,
        obj_id,
        scene_id,
    )


@app.cell
def _(
    FEATURES_INPUT_DIR_FULL,
    POINTS_PT_DIR_FULL,
    config,
    img_id,
    inst_idx,
    loader,
    np,
    obj_id,
    plot_mesh_instance_with_dgedi_features,
    scene_id,
):
    uid = loader.instance_uid(scene_id, img_id, obj_id, inst_idx)
    points_2 = np.load(POINTS_PT_DIR_FULL / (uid + ".npz"))["points"]
    features_ = np.load(FEATURES_INPUT_DIR_FULL / (uid + ".npz"))["features"]

    plot_mesh_instance_with_dgedi_features(
        loader, config, scene_id, img_id, inst_idx, points_2, features_
    )
    return


@app.cell
def _(
    FEATURES_INPUT_DIR_FULL,
    POINTS_PT_DIR_FULL,
    TARGET_DIR_FULL,
    exp2,
    loader,
):
    dataset, model, train_loss_history, val_loss_history = exp2(loader, POINTS_PT_DIR_FULL, FEATURES_INPUT_DIR_FULL, TARGET_DIR_FULL)
    return dataset, model, train_loss_history, val_loss_history


@app.cell
def _(
    dataset,
    evaluate_split,
    loader,
    model,
    plot_error_by_object,
    plot_error_distribution,
    plot_error_vs_visibility,
    plot_loss,
    plot_pred_vs_target,
    train_loss_history,
    val_loss_history,
):
    df = evaluate_split(model, dataset, split=2, loader=loader)

    plot_loss(train_loss_history, val_loss_history)
    plot_error_by_object(df)
    plot_error_distribution(df)
    plot_error_vs_visibility(df)   # requiere haber pasado loader a evaluate_split
    plot_pred_vs_target(df)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## MlFlow examples
    """)
    return


@app.cell
def _():
    return


@app.cell
def _():
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
