# Changing the parameters of a version that already exists on disk is an error, you should create a new section instead.

[rm_outliers_20_2_visib_10]
min_visib = 0.10
n_points = 1024
outliers = { nb_neighbors = 20, std = 2.0 }

[[rm_outliers_20_2_visib_10.sources]]
dataset = "pbr"
scenes = "2-3"

[[rm_outliers_20_2_visib_10.sources]]
dataset = "lmo"
scenes = [2]
